title: Document Splitter
description: This Add-On splits a document along a designated page.
type: object
documents:
  - selected
properties:
  page:
    title: Page number to split on. 
    type: integer
