title: Document Splitter
description: This Add-On splits a document along a designated page into two documents. If your document is 5 pages and you split on page 3 the resulting documents will be page 1 to 3 and 4 to 5. 
instructions: ''
type: object
documents:
  - selected
properties:
  page:
    title: Page number to split on. 
    type: integer
  project_id:
    title: Project ID
    type: integer
    description: Project ID of the project you would like to upload the documents to. 
  access_level:
    title: Access level for uploaded documents
    type: string
    default: private
    enum:
      - private
      - organization
      - public
required: 
  - page
categories:
  - file
