title: Document Splitter
description: This Add-On splits a document along a designated page. 
type: object
documents:
  - selected
properties:
  page:
    title: Page number to splt on. 
    type: integer
